# Copyright Contributors to the OpenImageIO project.
# SPDX-License-Identifier: Apache-2.0
# https://github.com/AcademySoftwareFoundation/OpenImageIO

name: CI

on:
  push:
    branches:
      - master

permissions: read-all


jobs:

  windows:
    name: "${{matrix.desc}} VS${{matrix.vsver}}"
    strategy:
      fail-fast: false
      matrix:
        include:
          - desc: windows-2019
            runner: windows-2019
            vsver: 2019
            generator: "Visual Studio 16 2019"
            openexr_ver: v2.5.8
            python_ver: 3.7
            simd: sse4.2
          # - desc: windows-2022
          #   runner: windows-2022
          #   vsver: 2022
          #   generator: "Visual Studio 17 2022"
          #   openexr_ver: main
          #   # v3.1.4
          #   python_ver: 3.7
          #   simd: sse4.2
    runs-on: ${{ matrix.runner }}
    env:
      PYTHON_VERSION: ${{matrix.python_ver}}
      CMAKE_GENERATOR: ${{matrix.generator}}
      OPENEXR_VERSION: ${{matrix.openexr_ver}}
      USE_SIMD: ${{matrix.simd}}
      CTEST_ARGS: "--timeout 180 --repeat after-timeout:6"
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2
      - name: Setup Nuget.exe
        uses: nuget/setup-nuget@b2bc17b761a1d88cab755a776c7922eb26eefbfa # v1.0.6
      - name: Build setup
        shell: bash
        run: |
            ${{matrix.setenvs}}
            src/build-scripts/ci-startup.bash
      - name: Dependencies
        shell: bash
        run: src/build-scripts/gh-win-installdeps.bash
      - name: Build
        shell: bash
        run: src/build-scripts/ci-build.bash
      - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
        name: Upload artifacts
        with:
          name: oiio-${{github.job}}-VS${{matrix.vsver}}
          path: |
            # TODO: Just grab this from the build dir?
            D:/a/OpenImageIO/OpenImageIO/dist/bin/
      # - name: Testsuite
      #   shell: bash
      #   run: src/build-scripts/ci-test.bash
      # - uses: actions/upload-artifact@3cea5372237819ed00197afe530f5a7ea3e805c8 # v3.1.0
      #   if: failure()
      #   with:
      #     name: oiio-${{github.job}}-VS${{matrix.vsver}}
      #     path: |
      #       build/cmake-save
      #       build/testsuite/*/*.*
      #       !build/testsuite/oiio-images
      #       !build/testsuite/openexr-images
      #       !build/testsuite/fits-images
      #       !build/testsuite/j2kp4files_v1_5
